### ISSUE TITLE
Export environmental variables into cf-ssh?

### ISSUE THREAD

**Issue by vzvenyach** [18F/cg-scripts#10]
Over the weekend, I finally got an app working using django and postgres. (Will likely submit PRs for the docs.18f.gov repo next week). One thing, though. When I used `cf-ssh`, I did not have the environmental variables. That's not _terrible_ because I could copy and paste, but if it's not too hard, it would be a nice feature to just have those environmental variables set.

**Comment by jmcarp** [comment]
`cf-ssh` isn't a thing anymore.
