### ISSUE TITLE
use new quota naming structure

### ISSUE THREAD

**Issue by afeld** [18F/cg-scripts#31]
Per @berndverst [in Slack](https://gsa-tts.slack.com/archives/cloud-gov-skyporter/p1479932190004143):

> For the quota naming, I’ve been using: `AGENCY-NAME_IAA-NUMBER_POPSTART-POPEND-01`

...where `POP` is "period of performance".

**Comment by berndverst** [comment]
e.g. `20161101-20171031-01` where 01 is a counter. If this quota already exists, increment the quota by one and create that instead.
