### ISSUE TITLE
add source for CF SSH

### ISSUE THREAD

**Issue by afeld** [18F/cg-scripts#4]
...or should it live in a standalone repo? Binary available here:

https://github.com/18F/cloud-foundry-scripts/releases/tag/v1

/cc @dlapiduz

**Comment by pkarman** [comment]
@dlapiduz ping

**Comment by jgrevich** [comment]
I too was looking for this in hopes of fixing: https://github.com/18F/Infrastructure/issues/614#issuecomment-217703001

**Comment by afeld** [comment]
https://github.com/cloudfoundry-community/cf-ssh/compare/master...dlapiduz:tmate-param

**Comment by dlapiduz** [comment]
Sorry about this. Here is the code: https://github.com/dlapiduz/cf-ssh/tree/18f.

I will cut a new version with a new 18f.gov url

**Comment by dlapiduz** [comment]
Here it is: https://github.com/18F/cg-scripts/releases/tag/v2
